version: '3'
services:

  frontend:
    build: ./frontend
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/home/node/dev
    depends_on:
    - backend

  backend:
    build: ./backend
    ports:
    - "3001:3000"
    volumes:
    - ./backend:/home/node/dev
    depends_on:
    - database
    networks: 
    - dbnet

  database:
    image: mariadb
    restart: always
    ports:
    - 3002:3306
    networks: 
    - dbnet
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: elearning
      MYSQL_PASSWORD: elearningpw
      MYSQL_DATABASE: elearning

networks: 
  dbnet: